name: Releases

on:
  push:
    tags:
      - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: resume.pdf
      - uses: actions/checkout@v4
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "resume.pdf"